name: External Trigger Main

on:
  workflow_dispatch:

jobs:
  external-trigger-fedora-xfce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: External Trigger
        if: github.ref == 'refs/heads/fedora-xfce'
        run: |
          echo "**** No external release, exiting ****"
          echo "No external release, exiting" >> $GITHUB_STEP_SUMMARY
          exit 0
